//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ModisenseDashboard", "Modisense_UserProfileModisense_SocialNetwork", "Modisense_UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gooddogs.Modules.Dnn.ModisenseDashboard.Data.Modisense_UserProfile), "Modisense_SocialNetwork", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gooddogs.Modules.Dnn.ModisenseDashboard.Data.Modisense_SocialNetwork))]
[assembly: EdmRelationshipAttribute("ModisenseDashboard", "Modisense_UserProfileModisense_Socialgraph", "Modisense_UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gooddogs.Modules.Dnn.ModisenseDashboard.Data.Modisense_UserProfile), "Modisense_Socialgraph", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gooddogs.Modules.Dnn.ModisenseDashboard.Data.Modisense_Socialgraph), true)]

#endregion

namespace Gooddogs.Modules.Dnn.ModisenseDashboard.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModisenseDashboardContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModisenseDashboardContainer object using the connection string found in the 'ModisenseDashboardContainer' section of the application configuration file.
        /// </summary>
        public ModisenseDashboardContainer() : base("name=ModisenseDashboardContainer", "ModisenseDashboardContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModisenseDashboardContainer object.
        /// </summary>
        public ModisenseDashboardContainer(string connectionString) : base(connectionString, "ModisenseDashboardContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModisenseDashboardContainer object.
        /// </summary>
        public ModisenseDashboardContainer(EntityConnection connection) : base(connection, "ModisenseDashboardContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Modisense_UserProfile> Modisense_UserProfile
        {
            get
            {
                if ((_Modisense_UserProfile == null))
                {
                    _Modisense_UserProfile = base.CreateObjectSet<Modisense_UserProfile>("Modisense_UserProfile");
                }
                return _Modisense_UserProfile;
            }
        }
        private ObjectSet<Modisense_UserProfile> _Modisense_UserProfile;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Modisense_Socialgraph> Modisense_Socialgraph
        {
            get
            {
                if ((_Modisense_Socialgraph == null))
                {
                    _Modisense_Socialgraph = base.CreateObjectSet<Modisense_Socialgraph>("Modisense_Socialgraph");
                }
                return _Modisense_Socialgraph;
            }
        }
        private ObjectSet<Modisense_Socialgraph> _Modisense_Socialgraph;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Modisense_POI> Modisense_POI
        {
            get
            {
                if ((_Modisense_POI == null))
                {
                    _Modisense_POI = base.CreateObjectSet<Modisense_POI>("Modisense_POI");
                }
                return _Modisense_POI;
            }
        }
        private ObjectSet<Modisense_POI> _Modisense_POI;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Modisense_SocialNetwork> Modisense_SocialNetwork
        {
            get
            {
                if ((_Modisense_SocialNetwork == null))
                {
                    _Modisense_SocialNetwork = base.CreateObjectSet<Modisense_SocialNetwork>("Modisense_SocialNetwork");
                }
                return _Modisense_SocialNetwork;
            }
        }
        private ObjectSet<Modisense_SocialNetwork> _Modisense_SocialNetwork;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modisense_UserProfile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModisense_UserProfile(Modisense_UserProfile modisense_UserProfile)
        {
            base.AddObject("Modisense_UserProfile", modisense_UserProfile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modisense_Socialgraph EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModisense_Socialgraph(Modisense_Socialgraph modisense_Socialgraph)
        {
            base.AddObject("Modisense_Socialgraph", modisense_Socialgraph);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modisense_POI EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModisense_POI(Modisense_POI modisense_POI)
        {
            base.AddObject("Modisense_POI", modisense_POI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modisense_SocialNetwork EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModisense_SocialNetwork(Modisense_SocialNetwork modisense_SocialNetwork)
        {
            base.AddObject("Modisense_SocialNetwork", modisense_SocialNetwork);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModisenseDashboard", Name="Modisense_POI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modisense_POI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Modisense_POI object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="other">Initial value of the Other property.</param>
        public static Modisense_POI CreateModisense_POI(global::System.Int32 id, global::System.Double latitude, global::System.Double longitude, global::System.String name, global::System.String category, global::System.String other)
        {
            Modisense_POI modisense_POI = new Modisense_POI();
            modisense_POI.Id = id;
            modisense_POI.Latitude = latitude;
            modisense_POI.Longitude = longitude;
            modisense_POI.Name = name;
            modisense_POI.Category = category;
            modisense_POI.Other = other;
            return modisense_POI;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Double _Latitude;
        partial void OnLatitudeChanging(global::System.Double value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Double _Longitude;
        partial void OnLongitudeChanging(global::System.Double value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Other
        {
            get
            {
                return _Other;
            }
            set
            {
                OnOtherChanging(value);
                ReportPropertyChanging("Other");
                _Other = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Other");
                OnOtherChanged();
            }
        }
        private global::System.String _Other;
        partial void OnOtherChanging(global::System.String value);
        partial void OnOtherChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModisenseDashboard", Name="Modisense_Socialgraph")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modisense_Socialgraph : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Modisense_Socialgraph object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        /// <param name="startTime">Initial value of the StartTime property.</param>
        /// <param name="endTime">Initial value of the EndTime property.</param>
        /// <param name="task">Initial value of the Task property.</param>
        /// <param name="taskCategory">Initial value of the TaskCategory property.</param>
        /// <param name="modisense_UserProfileId">Initial value of the Modisense_UserProfileId property.</param>
        public static Modisense_Socialgraph CreateModisense_Socialgraph(global::System.Int32 id, global::System.String latitude, global::System.String longitude, global::System.DateTime startTime, global::System.DateTime endTime, global::System.String task, global::System.String taskCategory, global::System.Int32 modisense_UserProfileId)
        {
            Modisense_Socialgraph modisense_Socialgraph = new Modisense_Socialgraph();
            modisense_Socialgraph.Id = id;
            modisense_Socialgraph.Latitude = latitude;
            modisense_Socialgraph.Longitude = longitude;
            modisense_Socialgraph.StartTime = startTime;
            modisense_Socialgraph.EndTime = endTime;
            modisense_Socialgraph.Task = task;
            modisense_Socialgraph.TaskCategory = taskCategory;
            modisense_Socialgraph.Modisense_UserProfileId = modisense_UserProfileId;
            return modisense_Socialgraph;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.String _Latitude;
        partial void OnLatitudeChanging(global::System.String value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.String _Longitude;
        partial void OnLongitudeChanging(global::System.String value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private global::System.DateTime _EndTime;
        partial void OnEndTimeChanging(global::System.DateTime value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Task
        {
            get
            {
                return _Task;
            }
            set
            {
                OnTaskChanging(value);
                ReportPropertyChanging("Task");
                _Task = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Task");
                OnTaskChanged();
            }
        }
        private global::System.String _Task;
        partial void OnTaskChanging(global::System.String value);
        partial void OnTaskChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskCategory
        {
            get
            {
                return _TaskCategory;
            }
            set
            {
                OnTaskCategoryChanging(value);
                ReportPropertyChanging("TaskCategory");
                _TaskCategory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskCategory");
                OnTaskCategoryChanged();
            }
        }
        private global::System.String _TaskCategory;
        partial void OnTaskCategoryChanging(global::System.String value);
        partial void OnTaskCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Modisense_UserProfileId
        {
            get
            {
                return _Modisense_UserProfileId;
            }
            set
            {
                OnModisense_UserProfileIdChanging(value);
                ReportPropertyChanging("Modisense_UserProfileId");
                _Modisense_UserProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modisense_UserProfileId");
                OnModisense_UserProfileIdChanged();
            }
        }
        private global::System.Int32 _Modisense_UserProfileId;
        partial void OnModisense_UserProfileIdChanging(global::System.Int32 value);
        partial void OnModisense_UserProfileIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModisenseDashboard", "Modisense_UserProfileModisense_Socialgraph", "Modisense_UserProfile")]
        public Modisense_UserProfile Modisense_UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modisense_UserProfile>("ModisenseDashboard.Modisense_UserProfileModisense_Socialgraph", "Modisense_UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modisense_UserProfile>("ModisenseDashboard.Modisense_UserProfileModisense_Socialgraph", "Modisense_UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Modisense_UserProfile> Modisense_UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modisense_UserProfile>("ModisenseDashboard.Modisense_UserProfileModisense_Socialgraph", "Modisense_UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Modisense_UserProfile>("ModisenseDashboard.Modisense_UserProfileModisense_Socialgraph", "Modisense_UserProfile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModisenseDashboard", Name="Modisense_SocialNetwork")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modisense_SocialNetwork : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Modisense_SocialNetwork object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Modisense_SocialNetwork CreateModisense_SocialNetwork(global::System.Int32 id, global::System.String name)
        {
            Modisense_SocialNetwork modisense_SocialNetwork = new Modisense_SocialNetwork();
            modisense_SocialNetwork.Id = id;
            modisense_SocialNetwork.Name = name;
            return modisense_SocialNetwork;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModisenseDashboard", "Modisense_UserProfileModisense_SocialNetwork", "Modisense_UserProfile")]
        public EntityCollection<Modisense_UserProfile> Modisense_UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Modisense_UserProfile>("ModisenseDashboard.Modisense_UserProfileModisense_SocialNetwork", "Modisense_UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Modisense_UserProfile>("ModisenseDashboard.Modisense_UserProfileModisense_SocialNetwork", "Modisense_UserProfile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModisenseDashboard", Name="Modisense_UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modisense_UserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Modisense_UserProfile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nickname">Initial value of the Nickname property.</param>
        public static Modisense_UserProfile CreateModisense_UserProfile(global::System.Int32 id, global::System.String nickname)
        {
            Modisense_UserProfile modisense_UserProfile = new Modisense_UserProfile();
            modisense_UserProfile.Id = id;
            modisense_UserProfile.Nickname = nickname;
            return modisense_UserProfile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nickname
        {
            get
            {
                return _Nickname;
            }
            set
            {
                OnNicknameChanging(value);
                ReportPropertyChanging("Nickname");
                _Nickname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nickname");
                OnNicknameChanged();
            }
        }
        private global::System.String _Nickname;
        partial void OnNicknameChanging(global::System.String value);
        partial void OnNicknameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModisenseDashboard", "Modisense_UserProfileModisense_SocialNetwork", "Modisense_SocialNetwork")]
        public EntityCollection<Modisense_SocialNetwork> Modisense_SocialNetwork
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Modisense_SocialNetwork>("ModisenseDashboard.Modisense_UserProfileModisense_SocialNetwork", "Modisense_SocialNetwork");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Modisense_SocialNetwork>("ModisenseDashboard.Modisense_UserProfileModisense_SocialNetwork", "Modisense_SocialNetwork", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModisenseDashboard", "Modisense_UserProfileModisense_Socialgraph", "Modisense_Socialgraph")]
        public EntityCollection<Modisense_Socialgraph> Modisense_Socialgraph
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Modisense_Socialgraph>("ModisenseDashboard.Modisense_UserProfileModisense_Socialgraph", "Modisense_Socialgraph");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Modisense_Socialgraph>("ModisenseDashboard.Modisense_UserProfileModisense_Socialgraph", "Modisense_Socialgraph", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
